### ISSUE TITLE
double dispatch

### ISSUE THREAD

**Issue by fabriziomoscon** [vzamishlyaev/crew-application#1]
https://github.com/vzamishlyaev/crew-application/blob/master/src/components/Filters/index.js#L42
https://github.com/vzamishlyaev/crew-application/blob/master/src/actions/Crew.js#L23-L27

Is there a way to make this code cleaner? It looks to me an additional complication to use a thunk for a synchronous call.

**Comment by vzamishlyaev** [comment]
Yes, you're right. I hurried. It looks better now:
https://github.com/vzamishlyaev/crew-application/blob/master/src/actions/Crew.js#L17
