### ISSUE TITLE
reduce build complexity

### ISSUE THREAD

**Issue by fabriziomoscon** [vzamishlyaev/crew-application#2]
It seems to me that this application configuration results from ejecting a project initialised with create-react-app. The result has many steps and configurations that are not necessary. Could you please perform some cleanup and leave only the strict necessary packages and configuration to build this project?

**Comment by vzamishlyaev** [comment]
Sorry, you're right. I've used original project from zip-file and I didn't pay attention to extra build stuff. It'll take some time to make it simpler.

**Comment by vzamishlyaev** [comment]
@fabriziomoscon I cleaned it up a bit. The build process is very simple now.
