### ISSUE TITLE
flow-type

### ISSUE THREAD

**Issue by fabriziomoscon** [vzamishlyaev/crew-application#4]
we rely on static type checking to protect against typing bugs, could you include an example in your project where you use flow-type?

**Comment by vzamishlyaev** [comment]
I added typing.

**Comment by fabriziomoscon** [comment]
@vzamishlyaev great.
Please note that in order to be checked by flow a file must start with `// @flow`.
Not asking you to change the the though.

**Comment by vzamishlyaev** [comment]
Yes, you're right. But I've added "all=true" to flow options and excluded everything except project sources. It should apply flow to all needed files if I am not mistaken.
